import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { Activity, AlertTriangle, ArrowRight, Check, ChevronRight, CircleHelp, ExternalLink, Eye, Fingerprint, KeyRound, LayoutDashboard, LockKeyhole, LogOut, Menu, Settings, Shield, UserRound, X } from 'lucide-react';
import { connectUrl, getJson, getMe, mutate, type Me } from './api';

type View = 'overview' | 'security' | 'account' | 'sessions' | 'activity' | 'alerts' | 'settings';
const nav: Array<{ id: View; label: string; icon: typeof LayoutDashboard }> = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'security', label: 'Security', icon: Shield }, { id: 'account', label: 'Roblox Account', icon: UserRound }, { id: 'sessions', label: 'Sessions', icon: Fingerprint }, { id: 'activity', label: 'Activity', icon: Activity }, { id: 'alerts', label: 'Alerts', icon: AlertTriangle }, { id: 'settings', label: 'Settings', icon: Settings }
];

export function App() {
  const [me, setMe] = useState<Me | null>(null); const [view, setView] = useState<View>('overview'); const [mobileOpen, setMobileOpen] = useState(false);
  const legalPage = window.location.pathname;
  if (['/privacy', '/terms', '/security', '/contact'].includes(legalPage)) return <LegalPage page={legalPage} />;
  useEffect(() => { getMe().then(setMe).catch(() => setMe({ connected: false, profile: null, scopes: [] })); }, []);
  if (!me?.connected) return <Landing configured={me !== null} />;
  return <div className="app-shell"><aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark"><Shield size={20} /></span><span>Roblox <b>Guardian</b></span></div><div className="nav-label">Workspace</div><nav>{nav.map(({ id, label, icon: Icon }) => <button className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => { setView(id); setMobileOpen(false); }} key={id}><Icon size={17} />{label}{id === 'alerts' && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-foot"><div className="privacy-mini"><LockKeyhole size={15} /><span>Official APIs only</span></div><a href="/privacy">Privacy center</a></div></aside><main className="main"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation"><Menu size={20} /></button><div><p className="eyebrow">Guardian workspace</p><h1>{nav.find((item) => item.id === view)?.label}</h1></div><div className="top-actions"><span className="connection-pill"><span className="status-dot" /> Connected</span><button className="icon-button" aria-label="Help"><CircleHelp size={19} /></button></div></header><div className="content"><ViewContent view={view} me={me} setMe={setMe} /></div></main></div>;
}

function Landing({ configured }: { configured: boolean }) { const params = new URLSearchParams(window.location.search); const error = params.get('error'); return <div className="landing"><div className="landing-noise" /><header className="landing-header"><div className="brand"><span className="brand-mark"><Shield size={20} /></span><span>Roblox <b>Guardian</b></span></div><span className="secure-label"><LockKeyhole size={14} /> Independent security companion</span></header><section className="hero"><div className="hero-copy"><div className="kicker"><span /> Transparent by design</div><h1>Your Roblox account.<br /><em>Protected by transparency.</em></h1><p>Connect through official Roblox authorization without sharing your Roblox password. See exactly what Guardian can and cannot access.</p><div className="hero-actions">{configured ? <a className="primary-button" href={connectUrl()}>Connect with Roblox <ArrowRight size={17} /></a> : <div className="setup-notice"><AlertTriangle size={17} /> Roblox OAuth is not configured.</div>}<a className="text-link" href="#transparency">Explore our boundaries <ChevronRight size={16} /></a></div>{error && <p className="error-text">Authorization could not be completed: {error.replaceAll('_', ' ')}</p>}</div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="shield-visual"><Shield size={95} strokeWidth={1.1} /><span className="shield-check"><Check size={19} /></span></div><div className="visual-caption"><span className="status-dot" /> OAuth connection ready</div></div></section><section className="proof-strip"><div><strong>01</strong><span>Official OAuth<br />authorization</span></div><div><strong>02</strong><span>No passwords<br />or cookies</span></div><div><strong>03</strong><span>Clear boundaries<br />you can verify</span></div></section><section className="transparency" id="transparency"><div><p className="eyebrow">The honest version</p><h2>What Guardian can<br />and cannot do.</h2></div><div className="boundary-grid"><Boundary title="What we can do" good items={['Authenticate through official Roblox OAuth', 'Read profile data you authorize', 'Manage Guardian sessions and alerts', 'Revoke our OAuth authorization']} /><Boundary title="What we cannot do" items={['Read passwords or .ROBLOSECURITY', 'Intercept Roblox traffic or client actions', 'Block Robux purchases or password changes', 'Access private data without authorization']} /></div></section><footer className="landing-footer"><span>Roblox Guardian is independent and not endorsed by Roblox Corporation.</span><span>Privacy&nbsp;&nbsp; Terms&nbsp;&nbsp; Security</span></footer></div>; }
function Boundary({ title, items, good }: { title: string; items: string[]; good?: boolean }) { return <div className={good ? 'boundary good' : 'boundary'}><h3>{good ? <Check size={17} /> : <X size={17} />}{title}</h3>{items.map((item) => <p key={item}><span>{good ? '+' : '—'}</span>{item}</p>)}</div>; }

function ViewContent({ view, me, setMe }: { view: View; me: Me; setMe: (me: Me) => void }) { const profile = me.profile; if (view === 'security') return <Security />; if (view === 'account') return <Account me={me} setMe={setMe} />; if (view === 'sessions') return <Sessions />; if (view === 'activity') return <ActivityView />; if (view === 'alerts') return <Alerts />; if (view === 'settings') return <SettingsView />; return <Overview profile={profile} />; }
function Overview({ profile }: { profile: Me['profile'] }) { return <><div className="welcome-row"><div><p className="eyebrow">Good to see you</p><h2>Security, made visible.</h2><p className="muted">Your Guardian connection is active and operating within the permissions you approved.</p></div><div className="connected-card"><span className="status-dot" /><div><b>Roblox connected</b><small>Authorization active</small></div><Check size={18} /></div></div><div className="metric-grid"><Metric icon={<Shield />} label="Protection status" value="Active" detail="Official API connection" /><Metric icon={<Fingerprint />} label="Guardian sessions" value="1" detail="Current device" /><Metric icon={<Eye />} label="Granted scopes" value="2" detail="openid · profile" /></div><div className="section-heading"><div><p className="eyebrow">Your connection</p><h3>Roblox account</h3></div><a className="subtle-link" href="#account">View details <ArrowRight size={14} /></a></div><AccountCard profile={profile} /></>; }
function Metric({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <div className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function AccountCard({ profile }: { profile: Me['profile'] }) { return <div className="account-card"><div className="avatar">{profile?.picture ? <img src={profile.picture} /> : <UserRound size={27} />}</div><div className="identity"><strong>{profile?.nickname ?? profile?.name ?? profile?.preferred_username ?? 'Roblox user'}</strong><span>@{profile?.preferred_username ?? 'authorized-user'}</span></div><div className="account-data"><span>User ID</span><b>{profile?.sub ?? 'Unavailable'}</b></div><div className="account-data"><span>Profile URL</span><b>{profile?.profile ? <a href={profile.profile} target="_blank">Open profile <ExternalLink size={12} /></a> : 'Unavailable'}</b></div><span className="verified-tag"><Check size={13} /> Verified via OAuth</span></div>; }
function Security() { return <><div className="page-intro"><p className="eyebrow">Security center</p><h2>Trust, with receipts.</h2><p className="muted">Guardian protects this application and stays clear about the controls that belong to Roblox.</p></div><div className="security-grid">{[['OAuth Security', 'Active', Shield], ['Guardian Session', 'Protected', Fingerprint], ['Roblox Password', 'Never requested', KeyRound], ['Roblox Cookies', 'Never requested', LockKeyhole], ['API Access', 'Official APIs only', Check]].map(([name, value, Icon]) => <div className="security-card" key={name as string}><Icon size={20} /><div><span>{name as string}</span><strong>{value as string}</strong></div><Check className="green-check" size={17} /></div>)}</div><div className="recommendations"><p className="eyebrow">Recommendations from Roblox</p><h3>Keep the account layer strong.</h3>{['Use Roblox 2-step verification', 'Review authorized applications regularly', 'Remove applications you no longer trust', 'Keep your email account secure'].map((item) => <div className="recommendation" key={item}><Check size={15} />{item}<ExternalLink size={14} /></div>)}</div></>; }
function Account({ me, setMe }: { me: Me; setMe: (me: Me) => void }) { const disconnect = async () => { await mutate('/api/oauth/revoke', 'POST'); setMe({ connected: false, profile: null, scopes: [] }); }; return <><div className="page-intro"><p className="eyebrow">Connected account</p><h2>Roblox account</h2><p className="muted">Only data returned by Roblox for your approved scopes appears here.</p></div><AccountCard profile={me.profile} /><div className="detail-panel"><div><p className="eyebrow">Authorization</p><h3>Granted scopes</h3><div className="scope-row">{me.scopes.map((scope) => <span key={scope}>{scope}</span>)}</div></div><div className="panel-actions"><button className="secondary-button" onClick={() => window.location.reload()}>Refresh connection</button><button className="danger-button" onClick={disconnect}>Disconnect Roblox</button></div></div></>; }
function Sessions() { const [sessions, setSessions] = useState<Array<{ id: string; userAgent: string; createdAt: string; current: boolean }>>([]); useEffect(() => { getJson<{ sessions: typeof sessions }>('/api/sessions').then((data) => setSessions(data.sessions)); }, []); const end = async (id?: string) => { await mutate(id ? `/api/sessions/${id}` : '/api/sessions', 'DELETE'); setSessions(id ? sessions.filter((item) => item.id !== id) : []); }; return <><div className="page-intro"><p className="eyebrow">Session control</p><h2>Guardian sessions</h2><p className="muted">These are sessions in Roblox Guardian, not Roblox account sessions.</p></div><div className="session-table"><div className="table-head"><span>Device</span><span>Created</span><span>Last active</span><span /></div>{sessions.map((session) => <div className="table-row" key={session.id}><div><Fingerprint size={18} /><b>{session.userAgent.includes('Chrome') ? 'Chrome browser' : 'Current browser'}</b>{session.current && <small>Current session</small>}</div><span>{new Date(session.createdAt).toLocaleDateString()}</span><span>Just now</span><button className="table-action" onClick={() => end(session.id)}><LogOut size={15} /> Sign out</button></div>)}{!sessions.length && <div className="empty-state"><Fingerprint size={25} /><b>No active sessions</b><span>Guardian sessions will appear here after you sign in.</span></div>}</div><div className="not-available"><AlertTriangle size={18} /><div><b>Roblox sessions</b><p>Roblox no proporciona actualmente esta información a esta aplicación mediante una API oficial.</p></div></div><button className="danger-button" onClick={() => end()}>Sign out all Guardian sessions</button></>; }
function ActivityView() { const [events, setEvents] = useState<Array<{ id: string; type: string; status: string; createdAt: string }>>([]); useEffect(() => { getJson<{ events: typeof events }>('/api/activity').then((data) => setEvents(data.events)); }, []); return <><div className="page-intro"><p className="eyebrow">Audit trail</p><h2>Activity</h2><p className="muted">A record of actions inside Roblox Guardian. Roblox account logins are not monitored.</p></div><div className="activity-list">{events.map((event) => <div className="activity-row" key={event.id}><div className="activity-icon"><Activity size={16} /></div><div><b>{event.type}</b><span>{new Date(event.createdAt).toLocaleString()}</span></div><span className="success-label"><Check size={13} />{event.status}</span></div>)}{!events.length && <div className="empty-state"><Activity size={25} /><b>No activity yet</b><span>Guardian events will appear as you use the workspace.</span></div>}</div><div className="not-available"><AlertTriangle size={18} /><div><b>Roblox login alerts</b><p>Los inicios de sesión de Roblox no están disponibles para monitorización mediante esta API.</p></div></div></>; }
function Alerts() { return <><div className="page-intro"><p className="eyebrow">Signal center</p><h2>Alerts</h2><p className="muted">Notifications generated by Roblox Guardian only.</p></div><div className="empty-state large"><AlertTriangle size={27} /><b>No unread alerts</b><span>OAuth authorization and Guardian security events will show up here.</span></div></>; }
function SettingsView() { return <><div className="page-intro"><p className="eyebrow">Workspace preferences</p><h2>Settings</h2><p className="muted">Control notifications for this application, not for Roblox.</p></div><div className="settings-panel"><Setting label="Guardian login" description="Notify me when a Guardian session is created" /><Setting label="OAuth authorization" description="Notify me when this connection changes" checked /><Setting label="Security confirmation" description="Notify me when a sensitive Guardian action is confirmed" checked /></div><div className="not-available"><LockKeyhole size={18} /><div><b>Roblox account settings</b><p>This action is administered directly by Roblox and cannot be controlled by Roblox Guardian.</p></div></div></>; }
function Setting({ label, description, checked }: { label: string; description: string; checked?: boolean }) { return <label className="setting"><span><b>{label}</b><small>{description}</small></span><input type="checkbox" defaultChecked={checked} /></label>; }

function LegalPage({ page }: { page: string }) { const content: Record<string, { title: string; body: string[] }> = {
  '/privacy': { title: 'Privacy', body: ['[LEGAL ENTITY NAME] operates Roblox Guardian as an independent application.', 'We use only information returned through the official Roblox OAuth scopes you approve. We do not request or store Roblox passwords, cookies, .ROBLOSECURITY, or MFA codes.', 'For privacy questions, contact [CONTACT EMAIL].'] },
  '/terms': { title: 'Terms', body: ['Roblox Guardian is provided by [LEGAL ENTITY NAME] under the laws of [JURISDICTION].', 'This application is not affiliated with, sponsored by, or endorsed by Roblox Corporation. Features that Roblox does not expose through official APIs are not provided here.', 'Business address: [BUSINESS ADDRESS].'] },
  '/security': { title: 'Security', body: ['Guardian keeps the Roblox client secret on the backend and uses Authorization Code with PKCE, state, nonce, strict redirect URIs, rate limiting, and HttpOnly session cookies.', 'Roblox account sessions, purchases, password changes, and email changes are not monitored or controlled unless Roblox officially exposes that capability to this application.'] },
  '/contact': { title: 'Contact', body: ['Security and privacy contact: [CONTACT EMAIL].', 'Legal entity: [LEGAL ENTITY NAME].', 'Jurisdiction: [JURISDICTION].'] }
}; const selected = content[page]; return <div className="legal-page"><a className="brand" href="/"><span className="brand-mark"><Shield size={20} /></span><span>Roblox <b>Guardian</b></span></a><main><p className="eyebrow">Roblox Guardian</p><h1>{selected.title}</h1>{selected.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<a className="text-link" href="/">Back to home <ArrowRight size={16} /></a></main></div>; }
